import json
import uuid

def generate_medium_questions():
    questions = []
    def add_q(topic, q, opts, ans, exp):
        questions.append({
            "id": f"py-medium-{uuid.uuid4().hex[:8]}",
            "language": "Python",
            "topic": topic,
            "difficulty": "Medium",
            "question": q,
            "options": opts,
            "correctAnswer": ans,
            "explanation": exp
        })

    # 1. Intro to Python
    add_q("Intro to Python", "How is memory managed in Python?", ["Manually using malloc()", "By the OS automatically", "Through a private heap managed by the Python memory manager", "It is not managed"], 2, "Python uses a private heap space and garbage collection to manage memory.")
    add_q("Intro to Python", "What is the GIL in CPython?", ["Global Interpreter Lock", "General Interface Language", "Global Integer Logic", "General Interpreter Lock"], 0, "The Global Interpreter Lock prevents multiple native threads from executing Python bytecodes at once.")
    add_q("Intro to Python", "What does it mean that Python is an 'interpreted' language?", ["It translates code directly to machine language before running", "It executes code line by line through an interpreter", "It requires a compilation step to an executable", "It is slower than JavaScript"], 1, "Interpreted means the Python interpreter executes the source code instruction by instruction.")
    add_q("Intro to Python", "What is bytecode in Python?", ["Machine code", "An intermediate, low-level representation of the source code", "A syntax error", "A type of variable"], 1, "Python compiles source code to an intermediate bytecode, which the Python Virtual Machine executes.")
    add_q("Intro to Python", "Which of the following is true regarding Python 2 and Python 3?", ["They are completely backward compatible", "Python 3 is a major revision and not fully backward compatible with Python 2", "Python 2 is faster", "There are no differences"], 1, "Python 3 introduced breaking changes (e.g., print as a function) to fix design flaws.")
    add_q("Intro to Python", "How do you check for the identity of an object in Python?", ["using the '==' operator", "using the 'is' operator", "using the 'equals()' method", "using the '===' operator"], 1, "The 'is' operator checks if two variables point to the same memory location.")
    add_q("Intro to Python", "What is a 'docstring' in Python?", ["A string that contains code", "A string used for commenting and documenting functions/classes", "A built-in data type", "A type of exception"], 1, "Docstrings (enclosed in triple quotes) are used to document modules, classes, and functions.")
    add_q("Intro to Python", "What does the `pass` statement do?", ["Raises an exception", "Exits the program", "Does nothing, used as a placeholder", "Skips an iteration in a loop"], 2, "The pass statement is a null operation; nothing happens when it executes.")
    add_q("Intro to Python", "Which module is commonly used for interacting with the operating system?", ["sys", "os", "system", "io"], 1, "The 'os' module provides a portable way of using operating system dependent functionality.")
    add_q("Intro to Python", "What is the purpose of `__name__ == '__main__'`?", ["To import a module", "To prevent a script from executing when imported as a module", "To define the main function", "To name the script"], 1, "It ensures that the block of code only runs if the script is executed directly, not when imported.")

    # 2. Variables & Data Types
    add_q("Variables & Data Types", "Which statement correctly assigns multiple variables to the same value?", ["x = y = z = 10", "x, y, z = 10", "x = 10, y = 10, z = 10", "10 = x = y = z"], 0, "Python allows chained assignment to assign the same value to multiple variables.")
    add_q("Variables & Data Types", "What is the data type of the result of `5 / 2` in Python 3?", ["int", "float", "double", "decimal"], 1, "True division (/) always returns a float in Python 3, even if the result is a whole number.")
    add_q("Variables & Data Types", "How do you represent a complex number in Python?", ["3 + 4i", "3 + 4j", "complex(3, 4i)", "3j4"], 1, "Python uses 'j' or 'J' to denote the imaginary part of a complex number.")
    add_q("Variables & Data Types", "What is the output of `type(None)`?", ["<class 'null'>", "<class 'NoneType'>", "<class 'None'>", "Error"], 1, "None is an object of its own type, NoneType.")
    add_q("Variables & Data Types", "Which of the following data types is immutable?", ["list", "set", "dictionary", "tuple"], 3, "Tuples are immutable sequences, unlike lists, sets, and dictionaries.")
    add_q("Variables & Data Types", "What is the value of `bool([])`?", ["True", "False", "None", "Error"], 1, "Empty collections (like empty lists) are considered 'falsy' and evaluate to False.")
    add_q("Variables & Data Types", "What does the `id()` function return?", ["The object's value", "The object's memory address/identity", "The object's data type", "The variable's name"], 1, "id() returns an integer representing the unique memory address of the object.")
    add_q("Variables & Data Types", "What is the result of `x = (5)`?", ["x is a tuple", "x is an integer", "x is a list", "SyntaxError"], 1, "Without a comma, (5) is just an integer in parentheses. A tuple requires a comma: (5,).")
    add_q("Variables & Data Types", "In Python, variables are essentially:", ["Containers storing values", "Pointers/References to objects in memory", "Typed memory blocks", "Constants"], 1, "Variables in Python act as names or references pointing to objects in memory.")
    add_q("Variables & Data Types", "What is the data type of `{'a', 'b', 'c'}`?", ["dictionary", "list", "tuple", "set"], 3, "Curly braces without key-value pairs create a set.")

    # 3. Sequence of Instructions
    add_q("Sequence of Instructions", "What is the effect of placing an assignment operation inside an `if` condition, e.g., `if (x = 5):`?", ["x becomes 5 and the block executes", "SyntaxError", "It checks if x equals 5", "x is ignored"], 1, "In Python, assignments cannot be used directly inside expressions unless using the walrus operator (:=).")
    add_q("Sequence of Instructions", "How does a `try-except` block alter the sequence of instructions?", ["It loops the instructions", "It skips instructions randomly", "It jumps to the except block if an error occurs, bypassing the rest of the try block", "It halts execution immediately"], 2, "An exception immediately transfers control to the nearest enclosing except block.")
    add_q("Sequence of Instructions", "In what order are arguments evaluated when passed to a function: `func(A(), B())`?", ["Right to left", "Left to right", "Simultaneously", "Depends on the function"], 1, "Python evaluates function arguments sequentially from left to right before calling the function.")
    add_q("Sequence of Instructions", "What happens if a function definition appears after the function call in a script?", ["It runs normally", "NameError: name is not defined", "The interpreter reorders the code", "SyntaxError"], 1, "Because Python executes top-to-bottom, the function must be defined before it is called.")
    add_q("Sequence of Instructions", "How do you split a long logical line into multiple physical lines?", ["Using a forward slash /", "Using a backslash \\", "Using a semicolon ;", "Using a comma ,"], 1, "A backslash \\ at the end of a line acts as a line continuation character.")
    add_q("Sequence of Instructions", "What happens to the sequence if `sys.exit()` is called?", ["The script restarts", "The function returns", "The script terminates immediately", "An exception is caught"], 2, "sys.exit() raises a SystemExit exception, terminating the sequence.")
    add_q("Sequence of Instructions", "Does Python support `goto` statements to jump around the sequence?", ["Yes", "No", "Only in Python 2", "Yes, using the `jump` keyword"], 1, "Python intentionally does not support goto statements to encourage structured programming.")
    add_q("Sequence of Instructions", "What does the `yield` keyword do to the sequence of instructions?", ["Pauses the function, saving its state, to be resumed later", "Stops the program", "Restarts the loop", "Yields CPU time to other threads"], 0, "yield turns a function into a generator, allowing it to pause and resume.")
    add_q("Sequence of Instructions", "How are default arguments evaluated in a function definition?", ["Every time the function is called", "Only once, when the function is defined", "At runtime", "They are not evaluated"], 1, "Default arguments are evaluated once at the time the function is defined (top-to-bottom execution).")
    add_q("Sequence of Instructions", "What is the output of `x=1; y=2; x,y = y,x+y; print(x,y)`?", ["2 3", "2 4", "1 2", "3 3"], 0, "The right-hand side is evaluated completely before assignment. y is 2, x+y is 3, so x becomes 2, y becomes 3.")

    # 4. Input & Output Basics
    add_q("Input & Output Basics", "How do you format a string to insert variables using f-strings?", ["'Hello {name}'", "f'Hello {name}'", "format('Hello {name}')", "f'Hello $name'"], 1, "Prefixing the string with 'f' allows embedding expressions inside curly braces.")
    add_q("Input & Output Basics", "What does `print(f'{3 * 4}')` output?", ["{3 * 4}", "12", "f'12'", "Error"], 1, "Expressions inside f-string braces are evaluated, resulting in '12'.")
    add_q("Input & Output Basics", "How can you read all lines from standard input until EOF?", ["sys.stdin.read()", "input().read()", "sys.read()", "input(EOF)"], 0, "sys.stdin.read() reads the entire standard input until EOF (Ctrl-D or Ctrl-Z).")
    add_q("Input & Output Basics", "What is the equivalent of `print('A', end=' ')` in older Python string formatting?", ["sys.stdout.write('A ')", "sys.print('A ')", "output('A ')", "console.log('A ')"], 0, "sys.stdout.write() allows direct writing to the output stream without automatic newlines.")
    add_q("Input & Output Basics", "What happens if you use `input()` and the user hits Enter without typing anything?", ["Raises an error", "Returns None", "Returns an empty string ''", "Returns 0"], 2, "Hitting enter immediately returns an empty string.")
    add_q("Input & Output Basics", "How do you format a float `x = 3.14159` to 2 decimal places using an f-string?", ["f'{x:2d}'", "f'{x.2f}'", "f'{x:.2f}'", "f'{x,2f}'"], 2, "The format specifier ':.2f' formats the float to 2 decimal places.")
    add_q("Input & Output Basics", "What does the `%s` format specifier do in `'Hello %s' % 'World'`?", ["Converts object to a string using str()", "Converts object to a string using repr()", "Raises an error", "Treats the object as a string literal"], 0, "%s is the old-style string formatting placeholder for strings.")
    add_q("Input & Output Basics", "Which built-in module provides functions to redirect standard output?", ["os", "sys", "redirect", "io"], 1, "The 'sys' module allows reassignment of sys.stdout to redirect print output.")
    add_q("Input & Output Basics", "How do you evaluate a string containing a Python expression safely?", ["eval()", "ast.literal_eval()", "exec()", "parse()"], 1, "ast.literal_eval() safely evaluates strings containing Python literals, whereas eval() is dangerous.")
    add_q("Input & Output Basics", "What does `print('a', 'b', file=sys.stderr)` do?", ["Prints 'a b' to the standard error stream", "Prints to a file named 'sys.stderr'", "Throws an error", "Prints in red text"], 0, "The 'file' parameter of print() allows you to redirect the output to another file-like object, like stderr.")

    # 5. Type Conversions
    add_q("Type Conversions", "What happens during `int('101', 2)`?", ["Converts '101' to integer 101", "Converts binary string '101' to integer 5", "Throws an error", "Converts integer 101 to binary"], 1, "The second argument specifies the base; base 2 converts binary to decimal.")
    add_q("Type Conversions", "What is the output of `str([1, 2, 3])`?", ["'1, 2, 3'", "'[1, 2, 3]'", "'123'", "Error"], 1, "str() on a list returns the string representation of the list including brackets.")
    add_q("Type Conversions", "How do you convert a string like '[1, 2]' into an actual list safely?", ["list('[1, 2]')", "eval('[1, 2]')", "json.loads('[1, 2]')", "set('[1, 2]')"], 2, "json.loads() or ast.literal_eval() are safe ways to parse string representations of lists.")
    add_q("Type Conversions", "What is the output of `bool([0])`?", ["True", "False", "None", "Error"], 0, "A list containing elements (even a 0) is not empty, so it is truthy.")
    add_q("Type Conversions", "What is the result of `float('inf')`?", ["Infinity", "Throws a ValueError", "0.0", "None"], 0, "Python can convert the string 'inf' or 'infinity' to a floating-point infinity representation.")
    add_q("Type Conversions", "How do you convert an integer to a hexadecimal string?", ["hex(255)", "hexadecimal(255)", "to_hex(255)", "base16(255)"], 0, "The hex() function converts an integer to a lowercase hexadecimal string prefixed with '0x'.")
    add_q("Type Conversions", "What does `tuple('abc')` return?", ["('abc',)", "('a', 'b', 'c')", "('a', 'b', 'c',)", "Error"], 1, "The tuple() constructor iterates over the string and creates a tuple of characters.")
    add_q("Type Conversions", "What is the result of `int(True) + int(False)`?", ["0", "1", "2", "Error"], 1, "True is 1, False is 0. 1 + 0 = 1.")
    add_q("Type Conversions", "Which function converts a unicode code point back into a character?", ["chr()", "ord()", "char()", "unichr()"], 0, "The chr() function takes an integer code point and returns the corresponding character.")
    add_q("Type Conversions", "What happens if you run `int('10.5')`?", ["Returns 10", "Returns 11", "Raises a ValueError", "Returns 10.5"], 2, "int() cannot parse strings containing decimal points directly; it expects whole number strings.")

    # 6. Relational Operations
    add_q("Relational Operations", "What is the result of `10 == 10.0`?", ["True", "False", "Error", "None"], 0, "Python evaluates the numerical values as equal, even though they are different types (int and float).")
    add_q("Relational Operations", "What is the result of `10 is 10.0`?", ["True", "False", "Error", "None"], 1, "The 'is' operator checks for object identity. An int and a float are different objects in memory.")
    add_q("Relational Operations", "How does Python evaluate `3 < 5 < 7`?", ["(3 < 5) and (5 < 7)", "3 < (5 < 7)", "(3 < 5) < 7", "SyntaxError"], 0, "Chained comparisons are implicitly combined with 'and'.")
    add_q("Relational Operations", "What is the result of `[1, 2] == [1, 2]`?", ["True", "False", "Error", "None"], 0, "The '==' operator checks if the contents of the lists are equivalent.")
    add_q("Relational Operations", "What is the result of `[1, 2] is [1, 2]`?", ["True", "False", "Error", "None"], 1, "Each list literal creates a new object in memory, so they do not share the same identity.")
    add_q("Relational Operations", "Which comparison is valid and evaluates to True?", ["'b' > 'a'", "'a' > 'b'", "'a' == 'A'", "10 > '5'"], 0, "Strings are compared by Unicode points. 'b' (98) is greater than 'a' (97).")
    add_q("Relational Operations", "What happens if you compare an integer and a string, like `5 < '10'`?", ["True", "False", "Raises a TypeError", "None"], 2, "Python 3 does not allow ordering comparisons (<, >) between different types like int and str.")
    add_q("Relational Operations", "What does `math.isclose(a, b)` do?", ["Checks if a and b have close memory addresses", "Checks if a and b are equal within a small tolerance", "Checks if a is less than b", "Rounds a to b"], 1, "math.isclose() is used for safe floating-point comparisons to account for precision issues.")
    add_q("Relational Operations", "What is the output of `'abc' >= 'abc'`?", ["True", "False", "Error", "None"], 0, "They are identical, so 'greater than or equal to' evaluates to True.")
    add_q("Relational Operations", "What is the result of `(1, 2, 3) < (1, 2, 4)`?", ["True", "False", "TypeError", "SyntaxError"], 0, "Tuples are compared element by element. 3 < 4 is True, so the whole expression is True.")

    # 7. Logical Operators
    add_q("Logical Operators", "What is the result of `'hello' and 'world'`?", ["'hello'", "'world'", "True", "False"], 1, "'and' returns the last evaluated truthy value, which is 'world' after evaluating both.")
    add_q("Logical Operators", "What is the result of `'' or 'fallback'`?", ["''", "'fallback'", "True", "False"], 1, "'' is falsy, so 'or' returns the second operand 'fallback'.")
    add_q("Logical Operators", "How is `not 1 == 2` evaluated?", ["(not 1) == 2", "not (1 == 2)", "not 1 (=) 2", "Error"], 1, "Comparison operators have higher precedence than 'not', so it evaluates as not (1 == 2).")
    add_q("Logical Operators", "What is the output of `any([False, 0, ''])`?", ["True", "False", "0", "''"], 1, "any() returns True if at least one element is truthy. Since all are falsy, it returns False.")
    add_q("Logical Operators", "What is the output of `all([True, 1, 'abc'])`?", ["True", "False", "1", "'abc'"], 0, "all() returns True if ALL elements are truthy.")
    add_q("Logical Operators", "What happens in `x = 5 > 3 or 10 / 0`?", ["ZeroDivisionError", "x is True", "x is False", "x is 10"], 1, "Due to short-circuiting, 5 > 3 is True, so 'or' stops and never evaluates 10 / 0.")
    add_q("Logical Operators", "Which operator does bitwise AND instead of logical AND?", ["and", "&&", "&", "%"], 2, "The single ampersand & is the bitwise AND operator.")
    add_q("Logical Operators", "What is the result of `not not True`?", ["True", "False", "SyntaxError", "None"], 0, "Double negation returns the original boolean value.")
    add_q("Logical Operators", "Can you use logical operators on custom objects?", ["Yes", "No", "Only if they inherit from bool", "Only 'not'"], 0, "Yes, by default objects are truthy, and you can define __bool__() to customize behavior.")
    add_q("Logical Operators", "What does `bool(None or [])` evaluate to?", ["True", "False", "None", "Error"], 1, "Both None and [] are falsy. 'or' returns [], and bool([]) is False.")

    # 8. Conditional Statements
    add_q("Conditional Statements", "What does the expression `x = 'Yes' if condition else 'No'` represent?", ["A syntax error", "A ternary conditional expression", "A while loop", "A nested if"], 1, "This is Python's concise ternary operator syntax.")
    add_q("Conditional Statements", "What happens if you have an `if` statement but no indented code block?", ["It is ignored", "It raises an IndentationError", "It acts like a pass statement", "It executes the next unindented line"], 1, "Python requires an indented block after a colon. If missing, it raises an IndentationError.")
    add_q("Conditional Statements", "How can you execute multiple statements on a single line under an `if`?", ["Using commas", "Using semicolons", "Using ampersands", "It's impossible"], 1, "You can separate statements with semicolons: `if True: x = 1; y = 2`, though it's discouraged.")
    add_q("Conditional Statements", "What is the output of:\nif 0:\n  print('A')\nelif {}:\n  print('B')\nelse:\n  print('C')", ["A", "B", "C", "Error"], 2, "Both 0 and an empty dict {} are falsy, so it falls through to 'C'.")
    add_q("Conditional Statements", "What structural feature replaced long if-elif-else chains in Python 3.10?", ["switch statements", "match-case (structural pattern matching)", "select-case", "goto statements"], 1, "Python 3.10 introduced the `match` statement for pattern matching.")
    add_q("Conditional Statements", "Can the condition in an `if` statement be a function call?", ["Yes, if the function returns a value", "No", "Yes, but only if it returns a boolean", "Only if the function has no arguments"], 0, "Yes, the returned value will be evaluated for truthiness.")
    add_q("Conditional Statements", "In an if-elif chain, when does the first `elif` condition get evaluated?", ["At the same time as `if`", "Only if the preceding `if` condition was False", "Always", "Only if the `else` block is missing"], 1, "elif is only evaluated if all preceding conditions were False.")
    add_q("Conditional Statements", "What is wrong with `if x = 10:`?", ["Missing parentheses", "Uses assignment '=' instead of equality '=='", "Nothing is wrong", "x must be defined inside the if"], 1, "The single '=' is for assignment and causes a SyntaxError in an if condition.")
    add_q("Conditional Statements", "What is the purpose of checking `if my_list:`?", ["Checks if the list exists in memory", "Checks if the list is not empty", "Checks if the list is a list type", "SyntaxError"], 1, "An empty list is falsy, so `if my_list:` efficiently checks if it contains elements.")
    add_q("Conditional Statements", "Is it possible to have an `else` block without an `if`?", ["Yes, in try/except and loops", "No, never", "Yes, as a standalone block", "Only in functions"], 0, "Yes, `else` can also be used in `for`/`while` loops and `try`/`except` blocks.")

    # 9. Nested Conditional Statements
    add_q("Nested Conditional Statements", "What problem does excessive nesting of conditionals cause?", ["Memory leaks", "Slow execution speed", "Poor code readability and maintainability", "SyntaxErrors"], 2, "Deep nesting makes code difficult to follow and maintain.")
    add_q("Nested Conditional Statements", "How can you often avoid a nested `if`?", ["By using a `while` loop", "By using the `and` operator to combine conditions", "By using the `pass` statement", "By using global variables"], 1, "Combining `if A:` and `if B:` into `if A and B:` reduces nesting.")
    add_q("Nested Conditional Statements", "What happens if an `else` clause is misaligned (wrong indentation) in nested conditionals?", ["It runs normally", "It raises an IndentationError or attaches to the wrong `if`", "It attaches to both `if`s", "The code crashes at runtime"], 1, "Indentation dictates structure; a misaligned else either causes an error or attaches to a different if, changing logic.")
    add_q("Nested Conditional Statements", "What is the output of:\nx = 5\nif x > 0:\n  if x % 2 == 0:\n    print('A')\nelse:\n  print('B')", ["A", "B", "Nothing", "Error"], 2, "x > 0 is True, but x % 2 == 0 is False. There is no inner else, so nothing prints.")
    add_q("Nested Conditional Statements", "In a nested `if`, can the inner block modify variables used in the outer block?", ["Yes", "No", "Only if declared global", "Only if they are lists"], 0, "Yes, variable scope in Python is at the function level, not block level.")
    add_q("Nested Conditional Statements", "Is it possible to nest an `if` inside a one-line ternary expression?", ["Yes, e.g., `A if cond1 else (B if cond2 else C)`", "No, ternary expressions cannot be nested", "Yes, but only twice", "No, it causes a SyntaxError"], 0, "Ternary operators can be nested, though it is often discouraged for readability.")
    add_q("Nested Conditional Statements", "When writing a nested conditional, which condition should ideally be placed on the outside?", ["The most complex one", "The one most likely to be False (fail fast)", "The one most likely to be True", "It doesn't matter"], 1, "Putting the condition most likely to fail on the outside prevents unnecessary evaluation of inner blocks.")
    add_q("Nested Conditional Statements", "What is the output of:\nif True:\n  if False:\n    print(1)\n  print(2)", ["1\n2", "2", "Nothing", "Error"], 1, "The inner if is False so 1 is skipped, but 2 is outside the inner if (aligned with it), so it prints.")
    add_q("Nested Conditional Statements", "Can you use `elif` to replace a nested `else: if:`?", ["Yes", "No", "Only for integers", "Only if there are 3 conditions"], 0, "`elif` is specifically designed to prevent the deep nesting caused by `else: if:` structures.")
    add_q("Nested Conditional Statements", "What is 'Guard Clause' (or Early Return) refactoring?", ["Adding more nested ifs to protect variables", "Inverting conditions and returning early to remove nested ifs", "Using try/except instead of if", "Deleting else blocks"], 1, "Guard clauses check for failure conditions and return early, keeping the 'happy path' un-nested.")

    # 10. Loops (while loop, for loop)
    add_q("Loops", "What does `enumerate(my_list)` do in a `for` loop?", ["Sorts the list", "Provides both the index and the value during iteration", "Counts the number of elements", "Removes duplicates"], 1, "enumerate() yields pairs containing a count (from start, which defaults to 0) and a value yielded by the iterable argument.")
    add_q("Loops", "What is the output of:\nfor x in [1, 2, 3]:\n  pass\nprint(x)", ["1", "2", "3", "NameError"], 2, "The loop variable `x` retains its last value (3) even after the loop terminates.")
    add_q("Loops", "How do you loop over a dictionary to get both keys and values?", ["for k, v in dict:", "for k, v in dict.keys():", "for k, v in dict.items():", "for k, v in dict.values():"], 2, "The items() method returns a view object of the dictionary's key-value tuple pairs.")
    add_q("Loops", "What happens if you modify a list while iterating over it with a `for` loop?", ["It works perfectly", "It causes a SyntaxError", "It can lead to unexpected behavior or skipped elements", "The loop stops immediately"], 2, "Modifying the length or order of a list while iterating over it directly messes up the internal index tracker.")
    add_q("Loops", "How can you safely remove elements from a list while looping over it?", ["Iterate over a copy of the list (e.g., `for item in lst[:]:`)", "Use a while loop", "Use list comprehensions", "All of the above"], 3, "Iterating over a copy, using a while loop with careful index management, or building a new list via comprehension are all safe.")
    add_q("Loops", "What is list comprehension?", ["A way to comment loops", "A concise way to create lists using a single line of loop syntax", "A function that summarizes a list", "An error message"], 1, "List comprehensions provide a concise way to create lists: `[x for x in iterable if condition]`.")
    add_q("Loops", "What does `range(10, 0, -1)` generate?", ["0 to 10", "1 to 10", "10 down to 1", "Error"], 2, "The third argument is the step. It counts backwards from 10 down to 1 (exclusive of 0).")
    add_q("Loops", "What is the output of:\ni = 0\nwhile i < 3:\n  i += 1\nelse:\n  print(i)", ["0", "2", "3", "Nothing"], 2, "The while loop finishes normally (no break), so the else block executes, printing the final value of i, which is 3.")
    add_q("Loops", "Which built-in function pairs elements from two lists simultaneously in a `for` loop?", ["pair()", "zip()", "combine()", "join()"], 1, "zip() takes iterables and aggregates them in a tuple, stopping when the shortest is exhausted.")
    add_q("Loops", "Is it possible to use a `for` loop without assigning the loop variable?", ["No, it's required", "Yes, conventionally by using `_` (underscore)", "Yes, by omitting the variable completely", "Only in while loops"], 1, "If you don't need the value, convention dictates using `_` as the throwaway variable name: `for _ in range(5):`.")

    # 11. String Methods
    add_q("String Methods", "What does `'ab'.zfill(4)` return?", ["'abab'", "'  ab'", "'00ab'", "'ab00'"], 2, "zfill() pads the string on the left with zeros to reach the specified width.")
    add_q("String Methods", "Which method checks if a string ends with a specific suffix?", ["endswith()", "ends_with()", "last()", "suffix()"], 0, "The endswith() method returns True if the string ends with the specified value.")
    add_q("String Methods", "What does `'hello'.count('l')` return?", ["1", "2", "3", "Error"], 1, "The count() method returns the number of non-overlapping occurrences of substring 'l'.")
    add_q("String Methods", "How is `find()` different from `index()`?", ["They are identical", "`index()` raises a ValueError if not found; `find()` returns -1", "`find()` raises a ValueError if not found; `index()` returns -1", "`find()` is for lists, `index()` is for strings"], 1, "`index()` is stricter and crashes if the substring is missing, while `find()` fails silently returning -1.")
    add_q("String Methods", "What is the output of `' a b '.strip()`?", ["'ab'", "'a b'", "' a b '", "'a b'"], 1, "strip() only removes leading and trailing whitespace, leaving internal spaces intact.")
    add_q("String Methods", "What does `'Title Case'.istitle()` evaluate to?", ["True", "False", "Error", "None"], 0, "istitle() returns True if the string follows title casing (each word capitalized).")
    add_q("String Methods", "What does `'a,b,c'.partition(',')` return?", ["['a', 'b', 'c']", "('a', ',', 'b,c')", "('a', 'b', 'c')", "'a b c'"], 1, "partition() returns a 3-tuple containing the part before the separator, the separator itself, and the part after.")
    add_q("String Methods", "Which method is used to center a string within a specific width using a fill character?", ["center()", "middle()", "align()", "justify()"], 0, "The center(width, fillchar) method centers the string.")
    add_q("String Methods", "What does `'abc'.isalpha()` do?", ["Checks if all characters are letters", "Checks if it is alphanumeric", "Checks if it is lowercase", "Converts to alphabet"], 0, "isalpha() returns True if all characters in the string are alphabetic and there is at least one character.")
    add_q("String Methods", "What is the output of `'Hello'.swapcase()`?", ["'hELLO'", "'hello'", "'HELLO'", "'olleH'"], 0, "swapcase() converts uppercase to lowercase and vice versa.")

    # 12. Nested Loops
    add_q("Nested Loops", "What is the time complexity (Big O) of traversing an NxN grid using a double nested loop?", ["O(N)", "O(N log N)", "O(N^2)", "O(1)"], 2, "Running a loop N times, inside another loop running N times, results in O(N*N) = O(N^2) complexity.")
    add_q("Nested Loops", "How do you completely exit out of two nested loops at once using standard control flow?", ["`break 2`", "`exit all`", "Use a boolean flag or a function `return`", "Just one `break` is enough"], 2, "Python has no labelled break. You must use a flag variable to trigger outer breaks, or return from a function, or raise an Exception.")
    add_q("Nested Loops", "What does the following print?\nfor i in range(2):\n  for j in range(2):\n    if i == j: break\n    print(i, j)", ["1 0", "0 0\n1 1", "0 1", "Nothing"], 0, "i=0, j=0 (breaks). i=1, j=0 (prints '1 0'). i=1, j=1 (breaks).")
    add_q("Nested Loops", "If you have a nested loop iterating over a 3D array (list of lists of lists), how many `for` loops are typical?", ["1", "2", "3", "4"], 2, "A 3D structure generally requires 3 nested loops to traverse all individual elements.")
    add_q("Nested Loops", "Can you use list comprehension to create a nested loop?", ["Yes, e.g., `[x*y for x in A for y in B]`", "No, list comprehensions only support single loops", "Yes, but only for numbers", "Only using the `nest` keyword"], 0, "Multiple `for` clauses in a list comprehension act like nested loops.")
    add_q("Nested Loops", "In `[x*y for x in A for y in B]`, which loop is the outer loop?", ["The first one (`for x in A`)", "The second one (`for y in B`)", "They execute in parallel", "It randomly decides"], 0, "List comprehensions process loops from left to right: the left-most is the outer loop.")
    add_q("Nested Loops", "What is the danger of nesting a database query inside a loop?", ["It causes syntax errors", "It causes the N+1 query problem, leading to terrible performance", "It deletes data", "It creates an infinite loop"], 1, "Executing a query inside a loop hits the database repeatedly, drastically slowing down the app (N+1 problem).")
    add_q("Nested Loops", "What is the output of:\nmatrix=[[1,2],[3,4]]\nfor row in matrix:\n  print(row[0])", ["1\n2", "1\n3", "3\n4", "Error"], 1, "It prints the first element of each inner list: 1, then 3.")
    add_q("Nested Loops", "How many times does 'Hi' print?\nfor i in [1,2]:\n  pass\n  for j in [1,2]:\n    print('Hi')", ["2", "4", "0", "8"], 1, "The pass statement does nothing. Outer runs 2 times, inner runs 2 times. 2 * 2 = 4.")
    add_q("Nested Loops", "Can you nest a `while` loop inside a `for` loop and vice-versa?", ["Yes, any loop can be nested within any other", "No, they must be the same type", "Yes, but `while` must be the outer loop", "Yes, but `for` must be the outer loop"], 0, "There are no restrictions on mixing loop types in nesting.")

    # 13. Loop Control Statements
    add_q("Loop Control Statements", "What happens if `continue` is the last statement in a loop body?", ["It causes an error", "It effectively does nothing, as the loop would reiterate anyway", "It breaks the loop", "It creates an infinite loop"], 1, "Since it's at the end of the block, jumping to the next iteration is what happens anyway, rendering it redundant.")
    add_q("Loop Control Statements", "In a `while True:` loop, what is the best way to prevent an infinite loop?", ["Use the `stop` keyword", "Use an `if` condition with a `break`", "Use `continue`", "Do nothing, Python stops it automatically"], 1, "You must manually check a termination condition and execute `break`.")
    add_q("Loop Control Statements", "What does the `else` block on a `for` loop do if the loop is empty (e.g., `for i in []:`)?", ["It raises an error", "It is skipped", "It executes immediately", "It enters an infinite loop"], 2, "If the iterable is empty, the loop completes without hitting a `break`, so the `else` block executes immediately.")
    add_q("Loop Control Statements", "Can `break` jump out of multiple nested loops at once?", ["Yes, using `break all`", "Yes, using `break 2`", "No, it only exits the innermost loop", "No, it exits the function"], 2, "Python's `break` only terminates the loop it is directly inside.")
    add_q("Loop Control Statements", "What is the output of:\nfor i in range(5):\n  if i == 3: pass\n  print(i, end='')", ["012", "0124", "01234", "Error"], 2, "`pass` does nothing, so it doesn't skip the print. All numbers 0 to 4 are printed.")
    add_q("Loop Control Statements", "What is a common use for the `pass` statement?", ["Exiting a loop early", "Creating an empty class or function structure (stubbing) without causing a syntax error", "Skipping to the next iteration", "Throwing an exception"], 1, "It is often used as a placeholder during development to make empty blocks syntactically valid.")
    add_q("Loop Control Statements", "What is the output of:\nfor i in range(3):\n  break\nelse:\n  print('Done')", ["Done", "Nothing", "0", "Error"], 1, "The loop hits `break` immediately. Because it was broken, the `else` block does NOT execute.")
    add_q("Loop Control Statements", "If a `try` block inside a loop raises an exception, does `continue` inside the `except` block work?", ["Yes, it jumps to the next loop iteration", "No, it raises a SyntaxError", "It jumps out of the loop", "It restarts the try block"], 0, "`continue` is perfectly valid inside an `except` block to ignore the error and proceed to the next iteration.")
    add_q("Loop Control Statements", "What happens to the loop index variable after a `break`?", ["It is set to None", "It is deleted", "It retains its value from the moment the break occurred", "It increments by 1"], 2, "The loop variable retains its current value, which can be inspected after the loop.")
    add_q("Loop Control Statements", "Does Python have a `goto` statement for loop control?", ["Yes, imported from the os module", "Yes, natively", "No, Python lacks a goto statement", "Yes, but only in Python 2"], 2, "Python deliberately omits `goto` to enforce structured programming patterns.")

    # 14. Comparing Strings & Naming Variables
    add_q("Comparing Strings & Naming Variables", "Why is it dangerous to name a variable `list` or `str` in Python?", ["It causes a SyntaxError", "It overrides the built-in functions, causing errors when you try to use them", "It crashes the OS", "Python automatically renames them"], 1, "Shadowing built-ins means you lose access to the original functions/types within that scope.")
    add_q("Comparing Strings & Naming Variables", "Which variable name follows PEP 8 conventions for a constant?", ["MAX_CONNECTIONS", "max_connections", "MaxConnections", "maxConnections"], 0, "Constants are typically written in ALL_CAPS with underscores.")
    add_q("Comparing Strings & Naming Variables", "What does a variable name starting with a single underscore (e.g., `_internal`) signify?", ["It is a truly private variable", "It is a weak internal use indicator (convention only)", "It is a global variable", "It is a syntax error"], 1, "It's a convention indicating the name is meant for internal use, but Python doesn't enforce strict privacy.")
    add_q("Comparing Strings & Naming Variables", "What happens when you compare `'10' > '2'`?", ["True", "False", "Error", "None"], 1, "Strings are compared lexicographically. The character '1' (49) is less than '2' (50), so it returns False.")
    add_q("Comparing Strings & Naming Variables", "What is the result of `len('a') == len('b')`?", ["True", "False", "Error", "None"], 0, "Both strings have a length of 1, so the lengths are equal.")
    add_q("Comparing Strings & Naming Variables", "Can a variable name start with a Unicode character (e.g., `ñúmero = 5`) in Python 3?", ["Yes, Python 3 supports full Unicode identifiers", "No, only ASCII is allowed", "Only if running on Linux", "Only if imported"], 0, "Python 3 natively supports Unicode characters in variable names.")
    add_q("Comparing Strings & Naming Variables", "What does a variable name with double leading underscores (e.g., `__mangled`) do in a class?", ["Makes it globally available", "Triggers name mangling to prevent accidental overriding by subclasses", "Creates a constant", "Generates an error"], 1, "Double underscores invoke name mangling, renaming it internally to `_ClassName__name`.")
    add_q("Comparing Strings & Naming Variables", "Which of these compares the identities (memory addresses) of two strings?", ["str1 == str2", "str1 = str2", "str1 is str2", "str1 equals str2"], 2, "The `is` operator compares object identities.")
    add_q("Comparing Strings & Naming Variables", "Due to string interning in CPython, what is the result of `a='hello'; b='hello'; print(a is b)`?", ["True", "False", "Error", "None"], 0, "CPython automatically interns small, identifier-like strings, making them point to the same memory location.")
    add_q("Comparing Strings & Naming Variables", "What is the output of `'Apple' == 'apple'.capitalize()`?", ["True", "False", "Error", "None"], 0, "capitalize() turns 'apple' into 'Apple', making them equal.")

    # 15. Lists
    add_q("Lists", "What is the time complexity of appending an item to the end of a list?", ["O(1) amortized", "O(N)", "O(log N)", "O(N^2)"], 0, "Appending to a list is typically O(1) because lists are over-allocated arrays under the hood.")
    add_q("Lists", "How do you create a shallow copy of a list `L`?", ["L.copy()", "L[:]", "list(L)", "All of the above"], 3, "All three methods successfully create a shallow copy of the list.")
    add_q("Lists", "What happens if you multiply a list by an integer, e.g., `[1, 2] * 3`?", ["The elements are multiplied: [3, 6]", "The list repeats: [1, 2, 1, 2, 1, 2]", "Error", "A nested list is created"], 1, "Multiplying a list by an integer N repeats the list contents N times.")
    add_q("Lists", "What does `lst[::2]` do?", ["Returns every 2nd element starting from index 0", "Reverses the list", "Returns the last 2 elements", "Returns elements up to index 2"], 0, "The third slice parameter is the step; `::2` steps by 2.")
    add_q("Lists", "What is the output of `len([[1, 2], [3, 4, 5]])`?", ["2", "5", "4", "Error"], 0, "The list contains 2 elements (both of which happen to be lists).")
    add_q("Lists", "Can you use a list as a dictionary key?", ["Yes", "No, because lists are mutable (unhashable)", "Only if the list contains strings", "Only if it is empty"], 1, "Dictionary keys must be hashable (immutable). Since lists are mutable, they cannot be keys.")
    add_q("Lists", "How do you unpack a list `[1, 2, 3]` into three variables?", ["x, y, z = [1, 2, 3]", "x; y; z = [1, 2, 3]", "unpack([1, 2, 3])", "x, y = [1, 2, 3]"], 0, "Python allows direct assignment/unpacking as long as the number of variables matches the list length.")
    add_q("Lists", "What is the output of `[1, 2, 3] == [1, 3, 2]`?", ["True", "False", "Error", "None"], 1, "List equality requires both the elements and their order to match exactly.")
    add_q("Lists", "What does the `+` operator do when applied to two lists?", ["Adds their corresponding elements together", "Concatenates the second list to the end of the first, returning a new list", "Modifies the first list in place", "Throws a TypeError"], 1, "It concatenates them, producing a new list.")
    add_q("Lists", "What happens when you do `L1 = [1, 2]; L2 = L1; L1[0] = 99`?", ["L2 is [1, 2]", "L2 is [99, 2]", "L2 throws an error", "L1 is a new list"], 1, "L1 and L2 reference the exact same list in memory. Modifying L1 modifies L2.")

    # 16. Working with Lists
    add_q("Working with Lists", "What is the time complexity of inserting an item at the beginning of a list `lst.insert(0, val)`?", ["O(1)", "O(N)", "O(log N)", "O(N^2)"], 1, "Inserting at index 0 requires shifting every other element in the underlying array by one, taking O(N) time.")
    add_q("Working with Lists", "What is the difference between `append()` and `extend()`?", ["They do the same thing", "`append()` adds its argument as a single element; `extend()` iterates over its argument and adds each element", "`extend()` is for strings, `append()` for numbers", "`extend()` creates a new list"], 1, "`append([1,2])` adds the list as one element. `extend([1,2])` adds 1 and 2 individually.")
    add_q("Working with Lists", "What does `lst.pop(1)` do?", ["Removes the value 1 from the list", "Removes and returns the element at index 1", "Raises an error", "Removes the last element"], 1, "pop(index) removes the item at the given index and returns it.")
    add_q("Working with Lists", "What happens if you use `remove(val)` and `val` is not in the list?", ["Nothing happens", "Returns False", "Raises a ValueError", "Raises an IndexError"], 2, "The remove() method throws a ValueError if the item is not found.")
    add_q("Working with Lists", "What does `sorted(lst, reverse=True)` do?", ["Sorts the list in place in descending order", "Returns a new list sorted in descending order", "Reverses the original list", "Throws an error"], 1, "sorted() returns a new sorted list, and reverse=True makes it descending.")
    add_q("Working with Lists", "How do you find the maximum value in a list of numbers?", ["lst.max()", "max(lst)", "maximum(lst)", "lst.highest()"], 1, "The built-in max() function takes an iterable and returns the largest item.")
    add_q("Working with Lists", "What does `sum([1, 2, '3'])` do?", ["Returns 6", "Returns '123'", "Raises a TypeError", "Returns 3"], 2, "sum() only works with numbers; adding an integer to a string raises a TypeError.")
    add_q("Working with Lists", "What is the output of `['a', 'b', 'c'].index('b')`?", ["0", "1", "2", "-1"], 1, "index('b') returns the index of the first occurrence of 'b', which is 1.")
    add_q("Working with Lists", "How do you create a list of numbers from 0 to 9?", ["list(range(10))", "list(10)", "range(0, 9)", "[0-9]"], 0, "range(10) generates the sequence, and list() converts it to a list.")
    add_q("Working with Lists", "What is the output of `x = [1, 2].append(3); print(x)`?", ["[1, 2, 3]", "3", "None", "Error"], 2, "List methods that modify the list in place (like append, sort, reverse) return None.")

    # 17. Lists and Strings
    add_q("Lists and Strings", "How can you check if the string 'apple' is an element of the list `fruits`?", ["'apple' in fruits", "fruits.contains('apple')", "'apple' == fruits", "fruits.has('apple')"], 0, "The 'in' operator checks for membership in a sequence.")
    add_q("Lists and Strings", "What is the output of `'abc' + ['d', 'e']`?", ["['a', 'b', 'c', 'd', 'e']", "'abcde'", "Raises a TypeError", "['abc', 'd', 'e']"], 2, "You cannot directly concatenate a string and a list using the + operator.")
    add_q("Lists and Strings", "What does `list('hello') == ['h', 'e', 'l', 'l', 'o']` evaluate to?", ["True", "False", "TypeError", "None"], 0, "list('hello') breaks the string into individual characters, matching the right side.")
    add_q("Lists and Strings", "If you split a string on a character that isn't present, e.g., `'hello'.split('z')`, what happens?", ["Returns an empty list", "Returns ['hello']", "Raises an error", "Returns None"], 1, "If the separator is not found, it returns a list containing the original string as the only element.")
    add_q("Lists and Strings", "How do you replace spaces with hyphens in a string using list methods?", ["'-'.join('a b c'.split())", "'a b c'.replace(' ', '-')", "Both A and B work", "Neither work"], 2, "Both approaches are valid, though replace() is more direct.")
    add_q("Lists and Strings", "What is the result of `''.join(['1', 2, '3'])`?", ["'123'", "Raises a TypeError", "'1 2 3'", "None"], 1, "join() expects an iterable of strings. Since 2 is an integer, it raises a TypeError.")
    add_q("Lists and Strings", "Are strings faster to modify than lists?", ["Yes, strings are optimized", "No, strings are immutable so modifying requires creating a completely new string", "They take the exact same time", "Depends on the characters"], 1, "String immutability means concatenating or modifying strings often creates new objects, which can be slower than appending to a list.")
    add_q("Lists and Strings", "What does `filter(str.isalpha, ['a', '1', 'b'])` effectively do?", ["Returns ['a', 'b']", "Returns ['1']", "Throws an error", "Returns nothing"], 0, "It filters the list, keeping only elements where str.isalpha returns True.")
    add_q("Lists and Strings", "How can you remove all empty strings `''` from a list of strings?", ["list.remove('')", "list.clear('')", "[s for s in list if s]", "delete list['']"], 2, "List comprehension `if s` filters out falsy values like empty strings.")
    add_q("Lists and Strings", "What is the result of `len(''.join(['a', 'bc', 'def']))`?", ["3", "6", "5", "Error"], 1, "The joined string is 'abcdef', which has a length of 6.")

    with open("scratch/python_mcq_medium.json", "w") as f:
        json.dump(questions, f, indent=2)

if __name__ == "__main__":
    generate_medium_questions()
