import { useState, useEffect } from "react";
import { motion } from "motion/react";
import { ArrowRight, Bot, Cpu, Briefcase, BarChart2, Award, Users, Terminal, Moon, Sun, ShieldCheck } from "lucide-react";
import { ApiService } from "../services/api";
import ResponsiveContainer from "../components/ResponsiveContainer";

interface LandingPageProps {
  onNavigate: (page: string) => void;
  user: any;
  theme: "light" | "dark";
  setTheme: (theme: "light" | "dark") => void;
}

export default function LandingPage({ onNavigate, user, theme, setTheme }: LandingPageProps) {
  const [stats, setStats] = useState({
    matchAccuracy: "98%",
    fasterPrep: "10x",
    averageAtsScore: "85+",
    agentCoverage: "24/7",
    totalExecutions: 0,
    uptime: "99.9%",
    activeAgentsCount: 6
  });

  useEffect(() => {
    async function loadStats() {
      try {
        const res = await ApiService.getPlatformStats();
        if (res) {
          setStats(res);
        }
      } catch (err) {
        console.error("Failed to load platform stats:", err);
      }
    }
    loadStats();
  }, []);

  const features = [
    {
      icon: Cpu,
      title: "ATS Optimization Engine",
      desc: "Simulate advanced applicant tracking filters to instantly identify match scores, keyword density, and format issues.",
      color: "from-purple-500/10 to-indigo-500/5",
      accent: "#6D5DF6"
    },
    {
      icon: Bot,
      title: "AI Interview Practice",
      desc: "Practice interview rounds generated by custom agents tailored to your exact experience level, receiving instant communications feedback.",
      color: "from-pink-500/10 to-purple-500/5",
      accent: "#8B5CF6"
    },
    {
      icon: BarChart2,
      title: "Skill Gap Analysis",
      desc: "Detect critical missing skills for your dream role and unlock an AI-formulated learning plan with direct study references.",
      color: "from-emerald-500/10 to-teal-500/5",
      accent: "#22C55E"
    },
    {
      icon: Briefcase,
      title: "Neural Job Matcher",
      desc: "Analyze your career profile against current industry standards and match to top prospective company roles.",
      color: "from-amber-500/10 to-orange-500/5",
      accent: "#F59E0B"
    },
    {
      icon: Award,
      title: "Hiring Predictor",
      desc: "Gain strategic insights with probabilistic percentage scores assessing candidate profile strengths, gaps, and action tips.",
      color: "from-cyan-500/10 to-blue-500/5",
      accent: "#3B82F6"
    },
    {
      icon: Users,
      title: "Multi-Agent Intelligence",
      desc: "A group of specialized cognitive agents working together to refine, score, and optimize your entire career pathway.",
      color: "from-fuchsia-500/10 to-pink-500/5",
      accent: "#EC4899"
    }
  ];

  return (
    <div className="relative min-h-screen transition-colors duration-300 bg-[var(--color-bg-page)] text-[var(--color-text-primary)] overflow-hidden pb-24 font-sans">
      
      {/* Premium Floating Background Blobs */}
      <motion.div
        animate={{
          y: [0, -40, 0],
          x: [0, 30, 0],
          rotate: [0, 360],
        }}
        transition={{
          duration: 20,
          repeat: Infinity,
          ease: "easeInOut",
        }}
        className="absolute top-[5%] left-[-5%] w-[450px] h-[450px] rounded-full bg-gradient-to-tr from-[#6D5DF6]/12 to-[#8B5CF6]/5 blur-[120px] pointer-events-none"
      />
      <motion.div
        animate={{
          y: [0, 50, 0],
          x: [0, -30, 0],
          rotate: [360, 0],
        }}
        transition={{
          duration: 25,
          repeat: Infinity,
          ease: "easeInOut",
        }}
        className="absolute bottom-[10%] right-[-5%] w-[550px] h-[550px] rounded-full bg-gradient-to-tr from-[#8B5CF6]/12 to-pink-500/5 blur-[140px] pointer-events-none"
      />
      <div className="absolute inset-0 bg-[linear-gradient(rgba(109,93,246,0.015)_1px,transparent_1px),linear-gradient(90deg,rgba(109,93,246,0.015)_1px,transparent_1px)] bg-[size:50px_50px] opacity-35" />

      {/* Navigation Header */}
      <header className="sticky top-0 z-40 border-b border-[var(--color-glass-border)] backdrop-blur-md bg-[var(--glass-card-bg)] shadow-[var(--glass-card-shadow)]">
        <ResponsiveContainer className="h-16 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-8 h-8 bg-gradient-to-br from-[#6D5DF6] to-[#8B5CF6] rounded-xl shadow-md shadow-indigo-500/20 flex items-center justify-center">
              <svg className="w-4.5 h-4.5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            <span className="text-lg font-black tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-[var(--color-text-primary)] to-[var(--color-text-secondary)]">
              SkillBridge
            </span>
            <span className="px-2 py-0.5 text-[9px] bg-[#6D5DF6]/10 border border-[#6D5DF6]/20 text-[#6D5DF6] rounded-lg font-mono font-bold uppercase">
              AI
            </span>
          </div>

          <div className="flex items-center space-x-4">
            {/* Theme Toggle Button */}
            <button
              onClick={() => setTheme(theme === "light" ? "dark" : "light")}
              className="p-2.5 rounded-2xl border border-[var(--color-glass-border)] bg-[var(--glass-card-bg)] shadow-[var(--clay-btn-secondary-shadow)] text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] transition duration-200 cursor-pointer"
            >
              {theme === "light" ? <Moon className="w-4 h-4" /> : <Sun className="w-4 h-4" />}
            </button>

            {user ? (
              <button
                onClick={() => onNavigate("dashboard")}
                className="px-5 py-2.5 clay-btn clay-btn-primary text-xs tracking-wider uppercase font-semibold"
              >
                Go to Dashboard
              </button>
            ) : (
              <>
                <button
                  onClick={() => onNavigate("login")}
                  className="px-4 py-2.5 text-xs font-mono font-semibold uppercase tracking-wider text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] transition"
                >
                  Log In
                </button>
                <button
                  onClick={() => onNavigate("signup")}
                  className="px-5 py-2.5 clay-btn clay-btn-primary text-xs font-mono font-semibold uppercase tracking-wider shadow-md"
                >
                  Sign Up
                </button>
              </>
            )}
          </div>
        </ResponsiveContainer>
      </header>

      {/* Hero Section */}
      <section className="pt-20 sm:pt-28 pb-12 text-center relative z-10">
        <ResponsiveContainer>
        <div className="inline-flex items-center space-x-2 px-3 py-1 bg-[#6D5DF6]/5 border border-[#6D5DF6]/15 rounded-full mb-8 backdrop-blur-xl">
          <Terminal className="w-3.5 h-3.5 text-[#6D5DF6]" />
          <span className="text-[10px] font-mono text-[var(--color-text-secondary)] tracking-wider uppercase font-bold">
            Cognitive Platform &bull; Gemini 2.5 Flash
          </span>
        </div>

        <motion.h1
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
          className="text-4xl sm:text-6xl font-black tracking-tight max-w-4xl mx-auto leading-tight"
        >
          Your AI-Powered Career{" "}
          <span className="bg-gradient-to-r from-[#6D5DF6] via-[#8B5CF6] to-pink-500 bg-clip-text text-transparent drop-shadow-[0_0_20px_rgba(109,93,246,0.15)]">
            Intelligence Platform
          </span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
          className="mt-6 text-sm sm:text-base text-[var(--color-text-secondary)] max-w-2xl mx-auto leading-relaxed font-semibold font-sans"
        >
          Optimize candidate assets, build customized study roadmaps, practice technical simulations, and match to premium roles with active recruiter analytics.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
          className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4 max-w-md mx-auto"
        >
          <button
            onClick={() => onNavigate(user ? "dashboard" : "signup")}
            className="w-full py-4 clay-btn clay-btn-primary text-xs tracking-wider uppercase font-semibold shadow-lg flex items-center justify-center space-x-2"
          >
            <span>Analyze Your Resume Now</span>
            <ArrowRight className="w-4 h-4" />
          </button>
          <button
            onClick={() => onNavigate("login")}
            className="w-full py-4 clay-btn clay-btn-secondary text-xs tracking-wider uppercase font-semibold"
          >
            Request Access Demo
          </button>
        </motion.div>
        </ResponsiveContainer>
      </section>

      {/* Features Bento Grid */}
      <section className="py-16 relative z-10">
        <ResponsiveContainer>
        <div className="text-center mb-16">
          <h2 className="text-2xl sm:text-4xl font-black tracking-tight">
            Integrated Multi-Agent Intelligence
          </h2>
          <p className="mt-3 text-xs sm:text-sm text-[var(--color-text-secondary)] font-sans max-w-xl mx-auto font-medium leading-relaxed">
            Multiple cognitive agents working asynchronously to evaluate, refine, and optimize your entire career portfolio.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feat, i) => {
            const IconComponent = feat.icon;
            return (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: i * 0.05, ease: [0.16, 1, 0.3, 1] }}
                whileHover={{ y: -6, scale: 1.01 }}
                className="relative group p-6 glass-card glowing-border flex flex-col justify-between h-[240px]"
              >
                <div>
                  <div className="p-3 bg-[var(--color-bg-page)] border border-[var(--color-border)] rounded-2xl w-fit text-[#6D5DF6] group-hover:text-[#8B5CF6] transition-colors duration-300 shadow-inner">
                    <IconComponent className="w-5.5 h-5.5" />
                  </div>
                  <h3 className="mt-5 text-base font-black text-[var(--color-text-primary)]">
                    {feat.title}
                  </h3>
                  <p className="mt-2 text-xs text-[var(--color-text-secondary)] leading-relaxed font-sans font-medium line-clamp-3">
                    {feat.desc}
                  </p>
                </div>
              </motion.div>
            );
          })}
        </div>
        </ResponsiveContainer>
      </section>

      {/* Proof Section */}
      <section className="py-12 text-center border-t border-[var(--color-border)] mt-12 space-y-6 relative z-10">
        <ResponsiveContainer className="space-y-6">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
          <div className="p-4 bg-[var(--glass-card-bg)] border border-[var(--color-glass-border)] rounded-3xl shadow-sm">
            <span className="block text-3xl font-black bg-gradient-to-r from-[#6D5DF6] to-[#8B5CF6] bg-clip-text text-transparent">
              {stats.matchAccuracy}
            </span>
            <span className="text-[10px] text-[var(--color-text-tertiary)] font-mono uppercase tracking-widest mt-1 block font-bold">
              Match Accuracy
            </span>
          </div>
          <div className="p-4 bg-[var(--glass-card-bg)] border border-[var(--color-glass-border)] rounded-3xl shadow-sm">
            <span className="block text-3xl font-black bg-gradient-to-r from-[#6D5DF6] to-[#8B5CF6] bg-clip-text text-transparent">
              {stats.fasterPrep}
            </span>
            <span className="text-[10px] text-[var(--color-text-tertiary)] font-mono uppercase tracking-widest mt-1 block font-bold">
              Faster Preparation
            </span>
          </div>
          <div className="p-4 bg-[var(--glass-card-bg)] border border-[var(--color-glass-border)] rounded-3xl shadow-sm">
            <span className="block text-3xl font-black bg-gradient-to-r from-[#6D5DF6] to-[#8B5CF6] bg-clip-text text-transparent">
              {stats.averageAtsScore}
            </span>
            <span className="text-[10px] text-[var(--color-text-tertiary)] font-mono uppercase tracking-widest mt-1 block font-bold">
              Average ATS Score
            </span>
          </div>
          <div className="p-4 bg-[var(--glass-card-bg)] border border-[var(--color-glass-border)] rounded-3xl shadow-sm">
            <span className="block text-3xl font-black bg-gradient-to-r from-[#6D5DF6] to-[#8B5CF6] bg-clip-text text-transparent">
              {stats.agentCoverage}
            </span>
            <span className="text-[10px] text-[var(--color-text-tertiary)] font-mono uppercase tracking-widest mt-1 block font-bold">
              Agent Coverage
            </span>
          </div>
        </div>

        {/* Live database stats badge */}
        <div className="inline-flex items-center space-x-2 px-4 py-2 bg-emerald-500/5 border border-emerald-500/15 rounded-full text-[10px] font-mono text-emerald-600 dark:text-emerald-400 backdrop-blur-sm">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
          <span>Live analytics processed from {stats.totalExecutions || 0} operations (Uptime: {stats.uptime})</span>
        </div>
        </ResponsiveContainer>
      </section>
    </div>
  );
}
