import { useState, useEffect } from "react";
import { motion } from "motion/react";
import { ArrowRight, Bot, Cpu, Briefcase, BarChart2, Award, Users, Terminal } from "lucide-react";
import { ApiService } from "../services/api";

interface LandingPageProps {
  onNavigate: (page: string) => void;
  user: any;
}

export default function LandingPage({ onNavigate, user }: LandingPageProps) {
  const [stats, setStats] = useState({
    matchAccuracy: "98%",
    fasterPrep: "10x",
    averageAtsScore: "85+",
    agentCoverage: "24/7",
    totalExecutions: 0,
    uptime: "99.9%",
    activeAgentsCount: 6
  });

  useEffect(() => {
    async function loadStats() {
      try {
        const res = await ApiService.getPlatformStats();
        if (res) {
          setStats(res);
        }
      } catch (err) {
        console.error("Failed to load platform stats:", err);
      }
    }
    loadStats();
  }, []);

  const features = [
    {
      icon: Cpu,
      title: "ATS Optimization Engine",
      desc: "Simulate advanced applicant tracking filters to identify matching scores, keyword density, and clear formatting fixes.",
      color: "from-blue-500/20 to-indigo-500/10",
      border: "hover:border-blue-500/30"
    },
    {
      icon: Bot,
      title: "AI Interview Simulation",
      desc: "Practice interview rounds generated by custom agents tailored to your precise experience level, receiving instant constructive scores.",
      color: "from-purple-500/20 to-pink-500/10",
      border: "hover:border-purple-500/30"
    },
    {
      icon: BarChart2,
      title: "Skill Gap & Roadmaps",
      desc: "Instantly detect critical missing skills for your dream role and unlock an AI-formulated multi-week learning plan with exact study resources.",
      color: "from-emerald-500/20 to-teal-500/10",
      border: "hover:border-emerald-500/30"
    },
    {
      icon: Briefcase,
      title: "Neural Job Matcher",
      desc: "Directly analyze your career profile against current industry standards and match to top prospective company roles.",
      color: "from-amber-500/20 to-orange-500/10",
      border: "hover:border-amber-500/30"
    },
    {
      icon: Award,
      title: "Hiring Predictor",
      desc: "Gain strategic insights with probabilistic percentage scores assessing your candidate profile strengths, gaps, and action tips.",
      color: "from-cyan-500/20 to-blue-500/10",
      border: "hover:border-cyan-500/30"
    },
    {
      icon: Users,
      title: "Multi-Agent Intelligence",
      desc: "Multiple specialized AI career agents work together to extract, refine, evaluate, and coach your entire path.",
      color: "from-violet-500/20 to-fuchsia-500/10",
      border: "hover:border-violet-500/30"
    }
  ];

  return (
    <div className="relative min-h-screen bg-[#020204] text-slate-100 selection:bg-blue-500/30 selection:text-white overflow-hidden pb-16">
      {/* Glow Effects */}
      <div className="absolute top-[-150px] left-[-100px] w-[600px] h-[600px] bg-blue-600/10 rounded-full blur-[140px] pointer-events-none"></div>
      <div className="absolute bottom-[-150px] right-[-100px] w-[600px] h-[600px] bg-purple-600/10 rounded-full blur-[140px] pointer-events-none"></div>

      {/* Navigation Header */}
      <header className="sticky top-0 z-40 backdrop-blur-2xl border-b border-white/5 bg-white/[0.02]">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg shadow-md shadow-blue-500/10 flex items-center justify-center">
              <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
            </div>
            <span className="text-lg font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400">
              SkillBridge
            </span>
            <span className="px-1.5 py-0.5 text-[9px] bg-white/10 border border-white/10 text-slate-300 rounded font-mono font-bold">
              AI
            </span>
          </div>

          <div className="flex items-center space-x-4">
            {user ? (
              <button
                onClick={() => onNavigate("dashboard")}
                className="px-4 py-2 text-sm font-semibold text-slate-300 hover:text-white transition duration-200"
              >
                Go to Dashboard
              </button>
            ) : (
              <>
                <button
                  onClick={() => onNavigate("login")}
                  className="px-4 py-2 text-sm font-semibold text-slate-300 hover:text-white transition duration-200"
                >
                  Log In
                </button>
                <button
                  onClick={() => onNavigate("signup")}
                  className="px-5 py-2 text-sm font-bold bg-blue-600 hover:bg-blue-500 shadow-xl shadow-blue-600/20 rounded-lg transition duration-200 text-white"
                >
                  Sign Up
                </button>
              </>
            )}
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="max-w-7xl mx-auto px-6 pt-16 sm:pt-24 pb-12 text-center relative">
        <div className="inline-flex items-center space-x-2 px-3 py-1 bg-white/5 border border-white/10 rounded-full mb-6 backdrop-blur-xl">
          <Terminal className="w-3.5 h-3.5 text-blue-400" />
          <span className="text-xs font-mono text-slate-400 tracking-wider uppercase">
            Powered by Gemini 2.5 Flash
          </span>
        </div>

        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-4xl sm:text-6xl font-extrabold tracking-tight max-w-4xl mx-auto leading-tight text-white"
        >
          Your AI-Powered Career{" "}
          <span className="bg-gradient-to-r from-blue-400 via-indigo-400 to-purple-500 bg-clip-text text-transparent drop-shadow-[0_0_20px_rgba(168,85,247,0.2)]">
            Intelligence Platform
          </span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.1 }}
          className="mt-6 text-base sm:text-lg text-slate-400 max-w-2xl mx-auto font-sans leading-relaxed"
        >
          Unlock ATS scoring, custom skill-gap roadmaps, real-time interactive interview practice, and personalized match recommendations tailored to your profile.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4"
        >
          <button
            onClick={() => onNavigate(user ? "dashboard" : "signup")}
            className="w-full sm:w-auto px-8 py-3.5 bg-blue-600 hover:bg-blue-500 shadow-xl shadow-blue-600/20 text-sm font-bold rounded-xl transition-all duration-200 flex items-center justify-center space-x-2 text-white"
          >
            <span>Analyze Your Resume Now</span>
            <ArrowRight className="w-4 h-4" />
          </button>
          <button
            onClick={() => onNavigate("login")}
            className="w-full sm:w-auto px-8 py-3.5 bg-white/5 border border-white/10 rounded-xl hover:bg-white/10 text-sm font-semibold text-slate-300 transition duration-200"
          >
            Schedule Demo
          </button>
        </motion.div>
      </section>

      {/* Features Bento Grid */}
      <section className="max-w-7xl mx-auto px-6 py-16">
        <div className="text-center mb-16">
          <h2 className="text-2xl sm:text-4xl font-extrabold tracking-tight text-white">
            Integrated Multi-Agent Intelligence
          </h2>
          <p className="mt-3 text-sm sm:text-base text-slate-400 font-sans max-w-xl mx-auto">
            A specialized collection of professional agents collaborating on every segment of your career strategy.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feat, i) => {
            const IconComponent = feat.icon;
            return (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: i * 0.05 }}
                className="relative group p-6 rounded-3xl bg-white/[0.02] border border-white/10 backdrop-blur-xl transition-all duration-300 hover:bg-white/[0.05] hover:border-white/20 hover:shadow-lg hover:shadow-blue-500/5 flex flex-col justify-between h-[230px]"
              >
                <div>
                  <div className="p-3 bg-white/5 border border-white/10 rounded-xl w-fit">
                    <IconComponent className="w-6 h-6 text-blue-400 group-hover:text-purple-400 transition-colors duration-300" />
                  </div>
                  <h3 className="mt-4 text-lg font-bold text-white group-hover:text-blue-300 transition-all">
                    {feat.title}
                  </h3>
                  <p className="mt-2 text-xs sm:text-sm text-slate-400 leading-relaxed font-sans line-clamp-3">
                    {feat.desc}
                  </p>
                </div>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* Proof Section */}
      <section className="max-w-7xl mx-auto px-6 py-12 text-center border-t border-white/5 mt-12 space-y-4">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
          <div>
            <span className="block text-3xl font-extrabold bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
              {stats.matchAccuracy}
            </span>
            <span className="text-xs text-slate-500 font-mono uppercase tracking-wider mt-1 block">
              Match Accuracy
            </span>
          </div>
          <div>
            <span className="block text-3xl font-extrabold bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
              {stats.fasterPrep}
            </span>
            <span className="text-xs text-slate-500 font-mono uppercase tracking-wider mt-1 block">
              Faster Preparation
            </span>
          </div>
          <div>
            <span className="block text-3xl font-extrabold bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
              {stats.averageAtsScore}
            </span>
            <span className="text-xs text-slate-500 font-mono uppercase tracking-wider mt-1 block">
              Average ATS Score
            </span>
          </div>
          <div>
            <span className="block text-3xl font-extrabold bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
              {stats.agentCoverage}
            </span>
            <span className="text-xs text-slate-500 font-mono uppercase tracking-wider mt-1 block">
              Agent Coverage
            </span>
          </div>
        </div>

        {/* Live database stats badge */}
        <div className="inline-flex items-center space-x-1.5 px-3 py-1 bg-emerald-500/5 border border-emerald-500/15 rounded-full text-[10px] font-mono text-emerald-400">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
          <span>Live platform analytics calculated from {stats.totalExecutions || 0} active database operations (Uptime: {stats.uptime})</span>
        </div>
      </section>
    </div>
  );
}
